name: ci
on:
  push: { branches: [ "main", "dev", "feature/**" ] }
  pull_request: { branches: [ "main", "dev" ] }
jobs:
  lint-type-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.10', cache: 'pip' }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint
        run: flake8 src tests
      - name: Type check
        run: mypy src
      - name: Test
        run: pytest
      - name: Upload coverage xml
        if: always()
        uses: actions/upload-artifact@v4
        with: { name: coverage-xml, path: coverage.xml, if-no-files-found: ignore }
