name: Test Pipeline

on: 
  push:
    branches: [ main ]

jobs:
  build: 
    runs-on: ubuntu-latest

    env: # add necessary environment variables here
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      LOG_FILE: src/app.log
      LOG_LEVEL: '0'
      # leave these blank - only here to pass tests in GH Actions
      FLASK_SECRET_KEY: ''
      AWS_ACCESS_KEY_ID: ''
      AWS_SECRET_ACCESS_KEY: ''
      AWS_DEFAULT_REGION: 'us-east-2'
      S3_BUCKET_NAME: 'team17-model-storage'
      AWS_COGNITO_USER_POOL_ID: ''
      AWS_COGNITO_CLIENT_ID: ''
      AWS_COGNITO_CLIENT_SECRET: ''
      DYNAMODB_ENDPOINT: 'http://localhost:8000'
      DYNAMOODB_TABLE_PREFIX: ''

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Run mypy
        run: mypy src/

      - name: Run Tests
        run: python -m pytest --cov=src --cov-report=term-missing tests/
